### ISSUE TITLE
Add a wiki for this?

### ISSUE THREAD

**Issue by BaaridunNasr** [lbernstone/ESP32_settimeofday#1]
In particular what each element of the program is going to do. That way it can act as a guide for newcomers.

**Comment by remcoNL** [comment]
I've another page for POSIX strings, really handy:

https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv

**Comment by lbernstone** [comment]
> I've another page for POSIX strings, really handy:
> 
> [nayarsystems/posix_tz_db:zones.csv@`master`](https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv)

ESP32 doesn't seem to like the bracket format, but very good list for named zones and DST.

**Comment by BaaridunNasr** [comment]
> ESP32 doesn't seem to like the bracket format, but very good list for named zones and DST.

Something like a parsing issue?
