### ISSUE TITLE
How to convert from GPS?

### ISSUE THREAD

**Issue by remcoNL** [lbernstone/ESP32_settimeofday#2]
TinyGPS++ has these output formats:

```
Serial.println(gps.date.value()); // Raw date in DDMMYY format (u32)
Serial.println(gps.date.year()); // Year (2000+) (u16)
Serial.println(gps.date.month()); // Month (1-12) (u8)
Serial.println(gps.date.day()); // Day (1-31) (u8)
Serial.println(gps.time.value()); // Raw time in HHMMSSCC format (u32)
Serial.println(gps.time.hour()); // Hour (0-23) (u8)
Serial.println(gps.time.minute()); // Minute (0-59) (u8)
Serial.println(gps.time.second()); // Second (0-59) (u8)
Serial.println(gps.time.centisecond()); // 100ths of a second (0-99) (u8)
```

As I understand the` settimeofday` needs UNIX time stamp. 

If I use `mktime` to calculate this time stamp it seems that the time is also set without timezone adjustment. 
If I use `setTime(hr,min,sec,day,mnth,yr);` the timezone adjustment is not applied (as expected).

Is there a way to convert the TinyGPS++ output so it will fit the settimeofday?

**Comment by remcoNL** [comment]
Using an algoritme that calculates the epoch seconds, it got it to work (avoiding mktime).

**Comment by viktak** [comment]
@remcoNL Would you mind sharing it? ;)

**Comment by remcoNL** [comment]
I continued with NTP server, and I cannot find my program back, sorry about that...

Maybe [this ](https://arduino.stackexchange.com/questions/71453/esp32-seconds-from-epoch) will help you? https://arduino.stackexchange.com/questions/71453/esp32-seconds-from-epoch

For setting the time I used this om the end (with the Timezone in EEPROM, set by the user):
```
configTime(0, 0, "pool.ntp.org");
  delay(100);
  EEPROM.get(404, TZ_current);
  char *p;
  p = TZ_current;
  setenv("TZ", p, 1);
  tzset();
```

**Comment by viktak** [comment]
Thank you!
